import { useState, useEffect, useMemo } from 'react';

/**
 * Language translations for the Mise app
 * This is extracted from Mise.jsx for reusability across components
 */
const translations = {
  en: {
    justTheRecipe: 'just the recipe',
    pasteUrl: 'Paste URL',
    snapPhoto: 'Photo',
    youtube: 'Video',
    recipesLeft: 'left',
    signIn: 'Sign In',
    logout: 'Logout',
    clean: 'Clean',
    addPhotos: 'Add photos',
    addMore: 'Add more',
    worksWithAny: 'Works with any recipe website',
    uploadOrSnap: 'Upload or snap cookbook pages',
    pasteYoutube: 'Paste a YouTube cooking video URL',
    youtubeHelper: 'Extract recipes from cooking videos',
    prep: 'Prep',
    cook: 'Cook',
    servings: 'Servings',
    viewSource: 'View source',
    save: 'Save',
    saved: 'Saved',
    saving: 'Saving...',
    upgrade: 'Upgrade',
    cookAgain: 'Cook Again',
    youllNeed: "You'll need:",
    tips: 'Tips',
    suggestFeature: 'Suggest a feature',
    savedRecipes: 'Saved Recipes',
    close: 'Close',
    noSavedRecipes: 'No saved recipes yet',
    createAccount: 'Create Account',
    welcomeBack: 'Welcome back',
    email: 'Email',
    password: 'Password',
    needAccount: "Need an account?",
    haveAccount: 'Have an account?',
    free: 'Free',
    recipes: 'recipes',
    month: 'month',
    unlimited: 'Unlimited',
    current: 'Current',
    choosePlan: 'Choose Plan',
    rateExperience: 'How was your cooking experience?',
    feedbackPlaceholder: "What feature would make mise better for you?",
    sendFeedback: 'Send',
    thanksFeedback: 'Thanks for your feedback!',
    newRecipe: '← New recipe',
    signInToSave: 'Sign in to save →',
    scaled: 'scaled',
    gathered: 'gathered',
    of: 'of',
    undo: 'Undo',
    tapIngredient: '👆 Tap each ingredient as you set it out',
    allGathered: '✓ All ingredients gathered!',
    startCooking: 'Start Cooking →',
    tapStep: '👆 Tap each step as you complete it',
    allDone: '🎉 Done! Enjoy your meal!',
    gotFeatureIdea: '💡 Got a feature idea?',
    usuallySeconds: 'Usually 15-25 seconds',
    usuallySecondsPhoto: 'Usually 20-30 seconds',
    back: '← Back',
    deleteRecipe: 'Delete',
    cookRecipe: 'Cook',
    gotAnIdea: 'Got an idea?',
    weShipWeekly: 'We ship updates weekly. Your suggestions become features.',
    weWillNotify: "We'll notify you when we build it.",
    whatWouldMakeBetter: 'What would make mise better?',
    send: 'Send',
    thanksFeedbackLong: 'Thanks! We read every message.',
    translateTo: 'Translate to',
    upgradeForTranslation: 'Upgrade for instant recipe translation',
    cancelAnytime: 'Cancel anytime. Secure payment via Stripe.',
  },
  es: {
    justTheRecipe: 'solo la receta',
    pasteUrl: 'Pegar URL',
    snapPhoto: 'Foto',
    youtube: 'Video',
    recipesLeft: 'restantes',
    signIn: 'Iniciar',
    logout: 'Salir',
    clean: 'Limpiar',
    addPhotos: 'Añadir fotos',
    addMore: 'Añadir más',
    worksWithAny: 'Funciona con cualquier sitio de recetas',
    uploadOrSnap: 'Sube o fotografía páginas de cocina',
    pasteYoutube: 'Pega una URL de video de cocina de YouTube',
    youtubeHelper: 'Extrae recetas de videos de cocina',
    prep: 'Prep',
    cook: 'Cocinar',
    servings: 'Porciones',
    viewSource: 'Ver fuente',
    save: 'Guardar',
    saved: 'Guardado',
    saving: 'Guardando...',
    upgrade: 'Mejorar',
    cookAgain: 'Cocinar de nuevo',
    youllNeed: 'Necesitarás:',
    tips: 'Consejos',
    suggestFeature: 'Sugerir función',
    savedRecipes: 'Recetas guardadas',
    close: 'Cerrar',
    noSavedRecipes: 'Aún no hay recetas guardadas',
    createAccount: 'Crear cuenta',
    welcomeBack: 'Bienvenido de nuevo',
    email: 'Correo',
    password: 'Contraseña',
    needAccount: '¿Necesitas una cuenta?',
    haveAccount: '¿Tienes cuenta?',
    free: 'Gratis',
    recipes: 'recetas',
    month: 'mes',
    unlimited: 'Ilimitado',
    current: 'Actual',
    choosePlan: 'Elegir plan',
    rateExperience: '¿Cómo fue tu experiencia cocinando?',
    feedbackPlaceholder: '¿Qué función mejoraría mise para ti?',
    sendFeedback: 'Enviar',
    thanksFeedback: '¡Gracias por tu opinión!',
    back: '← Volver',
    gotAnIdea: '¿Tienes una idea?',
    weShipWeekly: 'Actualizamos semanalmente. Tus sugerencias se convierten en funciones.',
    weWillNotify: 'Te avisaremos cuando lo construyamos.',
    whatWouldMakeBetter: '¿Qué mejoraría mise?',
    send: 'Enviar',
    thanksFeedbackLong: '¡Gracias! Leemos cada mensaje.',
    translateTo: 'Traducir a',
    upgradeForTranslation: 'Mejora para traducción instantánea de recetas',
    cancelAnytime: 'Cancela en cualquier momento. Pago seguro vía Stripe.',
  },
  fr: {
    justTheRecipe: 'juste la recette',
    pasteUrl: 'Coller URL',
    snapPhoto: 'Photo',
    youtube: 'Vidéo',
    recipesLeft: 'restantes',
    signIn: 'Connexion',
    logout: 'Déconnexion',
    clean: 'Nettoyer',
    addPhotos: 'Ajouter photos',
    addMore: 'Ajouter plus',
    worksWithAny: 'Fonctionne avec tous les sites de recettes',
    uploadOrSnap: 'Téléchargez ou photographiez des pages de cuisine',
    pasteYoutube: 'Collez une URL de vidéo de cuisine YouTube',
    youtubeHelper: 'Extraire des recettes de vidéos de cuisine',
    prep: 'Prép',
    cook: 'Cuisson',
    servings: 'portions',
    viewSource: 'Voir source',
    save: 'Sauver',
    saved: 'Sauvé',
    saving: 'Sauvegarde...',
    upgrade: 'Améliorer',
    cookAgain: 'Recuisiner',
    youllNeed: 'Vous aurez besoin:',
    tips: 'Conseils',
    suggestFeature: 'Suggérer une fonction',
    savedRecipes: 'Recettes sauvées',
    close: 'Fermer',
    noSavedRecipes: 'Pas encore de recettes sauvées',
    createAccount: 'Créer un compte',
    welcomeBack: 'Bienvenue',
    email: 'Email',
    password: 'Mot de passe',
    needAccount: 'Besoin d\'un compte?',
    haveAccount: 'Déjà un compte?',
    free: 'Gratuit',
    recipes: 'recettes',
    month: 'mois',
    unlimited: 'Illimité',
    current: 'Actuel',
    choosePlan: 'Choisir',
    rateExperience: 'Comment était votre expérience?',
    feedbackPlaceholder: 'Quelle fonction améliorerait mise?',
    sendFeedback: 'Envoyer',
    thanksFeedback: 'Merci pour votre avis!',
    back: '← Retour',
    gotAnIdea: 'Une idée?',
    weShipWeekly: 'Nous publions des mises à jour hebdomadaires. Vos suggestions deviennent des fonctionnalités.',
    weWillNotify: 'Nous vous préviendrons quand nous le construirons.',
    whatWouldMakeBetter: 'Qu\'est-ce qui améliorerait mise?',
    send: 'Envoyer',
    thanksFeedbackLong: 'Merci! Nous lisons chaque message.',
    translateTo: 'Traduire en',
    upgradeForTranslation: 'Améliorez pour la traduction instantanée des recettes',
    cancelAnytime: 'Annulez à tout moment. Paiement sécurisé via Stripe.',
  },
  pt: {
    justTheRecipe: 'só a receita',
    pasteUrl: 'Colar URL',
    snapPhoto: 'Foto',
    youtube: 'Vídeo',
    recipesLeft: 'restantes',
    signIn: 'Entrar',
    logout: 'Sair',
    clean: 'Limpar',
    addPhotos: 'Adicionar fotos',
    addMore: 'Adicionar mais',
    worksWithAny: 'Funciona com qualquer site de receitas',
    uploadOrSnap: 'Envie ou fotografe páginas de receitas',
    pasteYoutube: 'Cole uma URL de vídeo de culinária do YouTube',
    youtubeHelper: 'Extraia receitas de vídeos de culinária',
    prep: 'Prep',
    cook: 'Cozinhar',
    servings: 'porções',
    viewSource: 'Ver fonte',
    save: 'Salvar',
    saved: 'Salvo',
    saving: 'Salvando...',
    upgrade: 'Melhorar',
    cookAgain: 'Cozinhar novamente',
    youllNeed: 'Você vai precisar:',
    tips: 'Dicas',
    suggestFeature: 'Sugerir função',
    savedRecipes: 'Receitas salvas',
    close: 'Fechar',
    noSavedRecipes: 'Nenhuma receita salva ainda',
    createAccount: 'Criar conta',
    welcomeBack: 'Bem-vindo de volta',
    email: 'Email',
    password: 'Senha',
    needAccount: 'Precisa de uma conta?',
    haveAccount: 'Tem uma conta?',
    free: 'Grátis',
    recipes: 'receitas',
    month: 'mês',
    unlimited: 'Ilimitado',
    current: 'Atual',
    choosePlan: 'Escolher',
    rateExperience: 'Como foi sua experiência?',
    feedbackPlaceholder: 'Que função melhoraria o mise?',
    sendFeedback: 'Enviar',
    thanksFeedback: 'Obrigado pelo feedback!',
    back: '← Voltar',
    gotAnIdea: 'Tem uma ideia?',
    weShipWeekly: 'Lançamos atualizações semanalmente. Suas sugestões viram recursos.',
    weWillNotify: 'Avisaremos quando construirmos.',
    whatWouldMakeBetter: 'O que melhoraria o mise?',
    send: 'Enviar',
    thanksFeedbackLong: 'Obrigado! Lemos cada mensagem.',
    translateTo: 'Traduzir para',
    upgradeForTranslation: 'Melhore para tradução instantânea de receitas',
    cancelAnytime: 'Cancele a qualquer momento. Pagamento seguro via Stripe.',
  },
  zh: {
    justTheRecipe: '只要食谱',
    pasteUrl: '粘贴链接',
    snapPhoto: '照片',
    youtube: '视频',
    recipesLeft: '剩余',
    signIn: '登录',
    logout: '退出',
    clean: '整理',
    addPhotos: '添加照片',
    addMore: '添加更多',
    worksWithAny: '适用于任何食谱网站',
    uploadOrSnap: '上传或拍摄食谱页面',
    pasteYoutube: '粘贴YouTube烹饪视频链接',
    youtubeHelper: '从烹饪视频中提取食谱',
    prep: '准备',
    cook: '烹饪',
    servings: '份',
    viewSource: '查看来源',
    save: '保存',
    saved: '已保存',
    saving: '保存中...',
    upgrade: '升级',
    cookAgain: '再做一次',
    youllNeed: '你需要:',
    tips: '提示',
    suggestFeature: '建议功能',
    savedRecipes: '已保存的食谱',
    close: '关闭',
    noSavedRecipes: '还没有保存的食谱',
    createAccount: '创建账户',
    welcomeBack: '欢迎回来',
    email: '邮箱',
    password: '密码',
    needAccount: '需要账户?',
    haveAccount: '已有账户?',
    free: '免费',
    recipes: '食谱',
    month: '月',
    unlimited: '无限',
    current: '当前',
    choosePlan: '选择',
    rateExperience: '烹饪体验如何?',
    feedbackPlaceholder: '什么功能能让mise更好?',
    sendFeedback: '发送',
    thanksFeedback: '感谢您的反馈!',
    back: '← 返回',
    gotAnIdea: '有想法?',
    weShipWeekly: '我们每周发布更新。您的建议成为功能。',
    weWillNotify: '我们构建时会通知您。',
    whatWouldMakeBetter: '什么能让mise更好?',
    send: '发送',
    thanksFeedbackLong: '谢谢！我们阅读每条消息。',
    translateTo: '翻译成',
    upgradeForTranslation: '升级以获得即时食谱翻译',
    cancelAnytime: '随时取消。通过Stripe安全支付。',
  },
  hi: {
    justTheRecipe: 'सिर्फ रेसिपी',
    pasteUrl: 'URL पेस्ट करें',
    snapPhoto: 'फोटो',
    youtube: 'वीडियो',
    recipesLeft: 'बाकी',
    signIn: 'साइन इन',
    logout: 'लॉगआउट',
    clean: 'साफ करें',
    addPhotos: 'फोटो जोड़ें',
    addMore: 'और जोड़ें',
    worksWithAny: 'किसी भी रेसिपी वेबसाइट के साथ काम करता है',
    uploadOrSnap: 'कुकबुक पेज अपलोड या फोटो खींचें',
    pasteYoutube: 'YouTube कुकिंग वीडियो URL पेस्ट करें',
    youtubeHelper: 'कुकिंग वीडियो से रेसिपी निकालें',
    prep: 'तैयारी',
    cook: 'पकाना',
    servings: 'सर्विंग्स',
    viewSource: 'स्रोत देखें',
    save: 'सेव करें',
    saved: 'सेव हो गया',
    saving: 'सेव हो रहा है...',
    upgrade: 'अपग्रेड',
    cookAgain: 'फिर से बनाएं',
    youllNeed: 'आपको चाहिए:',
    tips: 'सुझाव',
    suggestFeature: 'सुझाव दें',
    savedRecipes: 'सेव की गई रेसिपी',
    close: 'बंद करें',
    noSavedRecipes: 'अभी तक कोई रेसिपी सेव नहीं',
    createAccount: 'खाता बनाएं',
    welcomeBack: 'वापसी पर स्वागत है',
    email: 'ईमेल',
    password: 'पासवर्ड',
    needAccount: 'खाता चाहिए?',
    haveAccount: 'खाता है?',
    free: 'मुफ्त',
    recipes: 'रेसिपी',
    month: 'महीना',
    unlimited: 'अनलिमिटेड',
    current: 'वर्तमान',
    choosePlan: 'चुनें',
    rateExperience: 'खाना बनाने का अनुभव कैसा था?',
    feedbackPlaceholder: 'कौन सी सुविधा mise को बेहतर बनाएगी?',
    sendFeedback: 'भेजें',
    thanksFeedback: 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    back: '← वापस',
    gotAnIdea: 'कोई विचार है?',
    weShipWeekly: 'हम साप्ताहिक अपडेट जारी करते हैं। आपके सुझाव सुविधाएँ बनते हैं।',
    weWillNotify: 'जब हम इसे बनाएंगे तो आपको सूचित करेंगे।',
    whatWouldMakeBetter: 'mise को क्या बेहतर बनाएगा?',
    send: 'भेजें',
    thanksFeedbackLong: 'धन्यवाद! हम हर संदेश पढ़ते हैं।',
    translateTo: 'अनुवाद करें',
    upgradeForTranslation: 'तत्काल रेसिपी अनुवाद के लिए अपग्रेड करें',
    cancelAnytime: 'कभी भी रद्द करें। Stripe के माध्यम से सुरक्षित भुगतान।',
  },
  ar: {
    justTheRecipe: 'فقط الوصفة',
    pasteUrl: 'لصق الرابط',
    snapPhoto: 'صورة',
    youtube: 'فيديو',
    recipesLeft: 'متبقي',
    signIn: 'تسجيل الدخول',
    logout: 'خروج',
    clean: 'تنظيف',
    addPhotos: 'إضافة صور',
    addMore: 'إضافة المزيد',
    worksWithAny: 'يعمل مع أي موقع وصفات',
    uploadOrSnap: 'ارفع أو صوّر صفحات كتاب الطبخ',
    pasteYoutube: 'الصق رابط فيديو طبخ من يوتيوب',
    youtubeHelper: 'استخرج الوصفات من فيديوهات الطبخ',
    prep: 'تحضير',
    cook: 'طبخ',
    servings: 'حصص',
    viewSource: 'عرض المصدر',
    save: 'حفظ',
    saved: 'محفوظ',
    saving: 'جاري الحفظ...',
    upgrade: 'ترقية',
    cookAgain: 'اطبخ مرة أخرى',
    youllNeed: 'ستحتاج:',
    tips: 'نصائح',
    suggestFeature: 'اقتراح ميزة',
    savedRecipes: 'الوصفات المحفوظة',
    close: 'إغلاق',
    noSavedRecipes: 'لا توجد وصفات محفوظة بعد',
    createAccount: 'إنشاء حساب',
    welcomeBack: 'مرحباً بعودتك',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    needAccount: 'تحتاج حساب؟',
    haveAccount: 'لديك حساب؟',
    free: 'مجاني',
    recipes: 'وصفات',
    month: 'شهر',
    unlimited: 'غير محدود',
    current: 'الحالي',
    choosePlan: 'اختر',
    rateExperience: 'كيف كانت تجربتك في الطبخ؟',
    feedbackPlaceholder: 'ما الميزة التي ستحسن mise؟',
    sendFeedback: 'إرسال',
    thanksFeedback: 'شكراً على رأيك!',
    back: '← رجوع',
    gotAnIdea: 'لديك فكرة؟',
    weShipWeekly: 'نطلق التحديثات أسبوعياً. اقتراحاتك تصبح ميزات.',
    weWillNotify: 'سنخبرك عندما نبنيها.',
    whatWouldMakeBetter: 'ما الذي سيحسن mise؟',
    send: 'إرسال',
    thanksFeedbackLong: 'شكراً! نقرأ كل رسالة.',
    translateTo: 'ترجمة إلى',
    upgradeForTranslation: 'ترقية للحصول على ترجمة فورية للوصفات',
    cancelAnytime: 'إلغاء في أي وقت. دفع آمن عبر Stripe.',
  },
};

/**
 * Available languages with their display labels
 */
export const languages = [
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'es', label: 'ES', name: 'Español' },
  { code: 'fr', label: 'FR', name: 'Français' },
  { code: 'pt', label: 'PT', name: 'Português' },
  { code: 'zh', label: '中文', name: 'Chinese' },
  { code: 'hi', label: 'हिं', name: 'Hindi' },
  { code: 'ar', label: 'عر', name: 'Arabic' },
];

/**
 * Hook for managing language state and translations
 * @returns {Object} { language, setLanguage, t, languages }
 */
export function useLanguage() {
  const [language, setLanguageState] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('mise_language') || 'en';
    }
    return 'en';
  });

  // Persist language changes to localStorage
  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('mise_language', language);
    }
  }, [language]);

  const setLanguage = (code) => {
    if (languages.some(lang => lang.code === code)) {
      setLanguageState(code);
    }
  };

  // Merge current language with English fallbacks
  const t = useMemo(() => {
    return { ...translations.en, ...(translations[language] || {}) };
  }, [language]);

  return {
    language,
    setLanguage,
    t,
    languages,
  };
}

export default useLanguage;
